version: '3'

services: 
    laravel:
        image: greg0x46/laravel:prod
        container_name: laravel
        networks: 
            - laranet

    nginx:
        image: greg0x46/nginx:prod
        container_name: nginx
        networks: 
            - laranet
        ports:
            - "8080:80"

networks: 
    laranet:
        driver: bridge